# -*- coding: utf-8-sig -*-
"""
En sık kullanılan 1000 Türkçe kelime.
Günlük bulmaca için başlangıç kelimeleri bu listeden seçilir.
"""

COMMON_TURKISH_WORDS: list[str] = [
    # Zamirler ve temel kelimeler
    "ben", "sen", "biz", "siz", "onlar", "bu", "şu",
    "kim", "ne", "nasıl", "neden", "nere", "hangi",
    # Fiiller
    "olmak", "etmek", "yapmak", "gelmek", "gitmek", "vermek", "almak",
    "görmek", "bilmek", "istemek", "demek", "söylemek", "bakmak",
    "bulmak", "düşünmek", "başlamak", "çalışmak", "kalmak", "oturmak",
    "yazmak", "okumak", "anlamak", "sevmek", "beklemek", "durmak",
    "koşmak", "yürümek", "açmak", "kapamak", "tutmak", "bırakmak",
    "taşımak", "koymak", "çıkmak", "girmek", "düşmek", "kalkmak",
    "uyumak", "yemek", "içmek", "konuşmak", "dinlemek", "öğrenmek",
    "öğretmek", "satmak", "çizmek", "oynamak", "kazanmak",
    "kaybetmek", "sormak", "cevaplamak", "değiştirmek", "büyümek",
    "küçülmek", "korkmak", "güvenmek", "hatırlamak", "unutmak",
    "geçmek", "dönmek", "uçmak", "yüzmek", "atlamak", "binmek",
    "inmek", "kesmek", "dikmek", "ekmek", "toplamak", "saymak",
    "ölçmek", "tartmak", "pişirmek", "temizlemek", "yıkamak",
    "giymek", "çıkarmak", "takmak", "vurmak", "çekmek", "itmek",
    "kırmak", "onarmak", "kurmak", "yıkmak", "doldurmak", "boşaltmak",
    # Sıfatlar
    "güzel", "çirkin", "büyük", "küçük", "uzun", "kısa",
    "geniş", "dar", "kalın", "ince", "ağır", "hafif",
    "hızlı", "yavaş", "sıcak", "soğuk", "sert", "yumuşak",
    "eski", "yeni", "genç", "yaşlı", "zengin", "fakir",
    "kolay", "zor", "doğru", "yanlış", "iyi", "kötü",
    "temiz", "kirli", "açık", "kapalı", "dolu", "boş",
    "tatlı", "acı", "tuzlu", "ekşi", "güçlü", "zayıf",
    "mutlu", "üzgün", "kızgın", "sakin", "sessiz", "gürültülü",
    "parlak", "karanlık", "beyaz", "siyah", "kırmızı", "mavi",
    "yeşil", "sarı", "turuncu", "mor", "pembe", "gri",
    "kahverengi", "altın", "gümüş", "düz", "eğri",
    "yuvarlak", "kare", "derin", "sığ", "taze", "bayat",
    # Aile ve insanlar
    "anne", "baba", "çocuk", "oğul", "kız", "kardeş",
    "abla", "ağabey", "dede", "nine", "amca", "dayı",
    "teyze", "hala", "kuzen", "eş", "arkadaş", "komşu",
    "öğretmen", "öğrenci", "doktor", "hemşire", "avukat", "mühendis",
    "polis", "asker", "çiftçi", "işçi", "memur", "müdür",
    "başkan", "lider", "patron", "şef", "garson", "berber",
    "terzi", "kasap", "fırıncı", "bakkal", "eczacı", "diş",
    "bebek", "genç", "kadın", "erkek", "insan", "toplum",
    # Vücut
    "baş", "göz", "kulak", "burun", "ağız", "dil",
    "el", "parmak", "kol", "bacak", "ayak", "kalp",
    "beyin", "kan", "kemik", "saç", "yüz", "boyun",
    "omuz", "sırt", "göğüs", "karın", "diz", "bilek",
    # Doğa
    "güneş", "ay", "yıldız", "dünya", "gökyüzü", "bulut",
    "yağmur", "kar", "rüzgar", "fırtına", "sel", "deprem",
    "dağ", "tepe", "vadi", "ova", "orman", "ağaç",
    "çiçek", "yaprak", "kök", "dal", "çimen", "toprak",
    "taş", "kaya", "kum", "deniz", "okyanus", "göl",
    "nehir", "çay", "şelale", "ada", "sahil", "plaj",
    "mağara", "volkan", "çöl", "buz", "ateş", "duman",
    "alev", "hava", "iklim", "mevsim", "ilkbahar", "yaz",
    "sonbahar", "kış", "gece", "gündüz", "sabah", "öğle",
    "akşam", "şafak", "gün", "hafta", "ay", "yıl",
    # Hayvanlar
    "kedi", "köpek", "kuş", "balık", "at", "inek",
    "koyun", "keçi", "tavuk", "horoz", "ördek", "kaz",
    "arı", "karınca", "kelebek", "örümcek", "yılan", "kurbağa",
    "kaplumbağa", "timsah", "aslan", "kaplan", "ayı", "kurt",
    "tilki", "tavşan", "fare", "sincap", "maymun", "fil",
    "zürafa", "deve", "yunus", "balina", "köpekbalığı", "kartal",
    "baykuş", "papağan", "penguen", "yarasa", "böcek", "sinek",
    "sivrisinek", "akrep",
    # Yiyecek ve içecek
    "ekmek", "su", "süt", "çay", "kahve", "meyve",
    "sebze", "et", "tavuk", "balık", "pirinç", "makarna",
    "peynir", "yoğurt", "tereyağı", "yumurta", "şeker", "tuz",
    "biber", "soğan", "sarımsak", "domates", "salatalık", "patates",
    "havuç", "kabak", "patlıcan", "fasulye", "mercimek", "nohut",
    "elma", "portakal", "muz", "üzüm", "çilek", "karpuz",
    "kavun", "şeftali", "kiraz", "erik", "armut", "limon",
    "zeytin", "fındık", "ceviz", "badem", "pilav", "çorba",
    "salata", "börek", "simit", "pasta", "dondurma", "bal",
    "reçel", "turşu",
    # Ev ve eşyalar
    "ev", "oda", "kapı", "pencere", "duvar", "tavan",
    "zemin", "merdiven", "balkon", "bahçe", "mutfak", "banyo",
    "yatak", "masa", "sandalye", "koltuk", "dolap", "ayna",
    "lamba", "perde", "halı", "yastık", "battaniye", "havlu",
    "tabak", "bardak", "kaşık", "çatal", "bıçak", "tencere",
    "tava", "fırın", "buzdolabı", "televizyon", "telefon",
    "bilgisayar", "saat", "anahtar", "kilit", "çanta",
    # Giyim
    "elbise", "gömlek", "pantolon", "etek", "ceket", "palto",
    "ayakkabı", "çorap", "şapka", "eldiven", "atkı", "kravat",
    "kemer", "düğme", "cep", "kumaş", "ipek", "pamuk",
    "deri", "yün",
    # Ulaşım
    "araba", "otobüs", "tren", "uçak", "gemi", "bisiklet",
    "motosiklet", "taksi", "tramvay", "metro", "köprü", "tünel",
    "yol", "cadde", "sokak", "kavşak", "park", "otopark",
    "benzin", "tekerlek", "motor", "fren", "direksiyon", "kask",
    # Şehir ve yapılar
    "şehir", "köy", "kasaba", "mahalle", "bina", "apartman",
    "okul", "hastane", "cami", "kilise", "kütüphane", "müze",
    "tiyatro", "sinema", "stadyum", "market", "çarşı", "pazar",
    "banka", "postane", "otel", "restoran", "kafe", "fabrika",
    "havaalanı", "liman", "istasyon", "hastane",
    # Eğitim ve bilim
    "kitap", "defter", "kalem", "kağıt", "tahta", "sınıf",
    "ders", "sınav", "not", "ödev", "diploma", "üniversite",
    "bilim", "matematik", "fizik", "kimya", "biyoloji", "tarih",
    "coğrafya", "edebiyat", "felsefe", "sanat", "müzik", "resim",
    "heykel", "şiir", "roman", "hikaye", "makale", "gazete",
    "dergi", "haber", "araştırma", "deney", "teori", "formül",
    # İş ve ekonomi
    "para", "banka", "kredi", "borç", "maaş", "vergi",
    "fiyat", "ucuz", "pahalı", "indirim", "kâr", "zarar",
    "şirket", "mağaza", "dükkan", "ticaret", "piyasa", "ekonomi",
    "bütçe", "yatırım", "sigorta", "emekli", "sendika",
    # Hukuk ve devlet
    "kanun", "hak", "adalet", "mahkeme", "hakim", "savcı",
    "suç", "ceza", "hapis", "özgürlük", "demokrasi", "seçim",
    "oy", "parti", "hükümet", "meclis", "anayasa", "vatan",
    "millet", "bayrak", "sınır", "pasaport", "vize",
    # Duygular ve soyut kavramlar
    "sevgi", "aşk", "nefret", "korku", "umut", "hayal",
    "rüya", "gerçek", "yalan", "sır", "güven", "inanç",
    "din", "tanrı", "ruh", "akıl", "düşünce", "fikir",
    "plan", "hedef", "amaç", "başarı", "zafer", "yenilgi",
    "barış", "savaş", "tehlike", "güvenlik", "risk", "şans",
    "kader", "talih", "mutluluk", "huzur", "özlem", "merak",
    "şaşkınlık", "gurur", "utanç", "kıskançlık", "öfke", "sabır",
    "cesaret", "korkaklık", "dürüstlük", "sadakat", "ihanet",
    "dostluk", "düşmanlık", "yalnızlık",
    # Zaman
    "zaman", "dakika", "saniye", "bugün", "dün", "yarın",
    "önce", "sonra", "şimdi", "geçmiş", "gelecek", "tarih",
    "takvim", "dönem", "çağ", "asır", "süre", "erken",
    "geç", "hemen", "bazen", "sık", "nadir", "daima",
    "hiç", "her",
    # Sağlık
    "sağlık", "hastalık", "ilaç", "ağrı", "ateş", "yara",
    "ameliyat", "tedavi", "aşı", "mikrop", "virüs", "bakteri",
    "kanser", "grip", "alerji", "tansiyon", "diyabet", "kalp",
    "nefes", "öksürük", "hapşırık", "baş ağrısı",
    # Spor ve eğlence
    "futbol", "basketbol", "voleybol", "tenis", "yüzme", "koşu",
    "boks", "güreş", "jimnastik", "kayak", "golf", "satranç",
    "oyun", "maç", "takım", "gol", "hakem", "skor",
    "şampiyon", "turnuva", "olimpiyat", "antrenman", "stadyum",
    # Teknoloji
    "teknoloji", "internet", "program", "yazılım", "donanım", "ekran",
    "klavye", "fare", "şifre", "veri", "dosya", "belge",
    "mesaj", "eposta", "uygulama", "robot", "yapay", "zeka",
    "enerji", "elektrik", "pil", "kablo", "uydu", "radar",
    # Coğrafya ve ülkeler
    "türkiye", "istanbul", "ankara", "izmir", "avrupa", "asya",
    "afrika", "amerika", "dünya", "kıta", "ülke", "başkent",
    "nüfus", "harita", "pusula", "ekvator", "kutup",
    # Müzik ve sanat
    "şarkı", "melodi", "ritim", "enstrüman", "gitar", "piyano",
    "davul", "keman", "flüt", "konser", "sahne", "orkestra",
    "dans", "bale", "tablo", "sergi", "fotoğraf", "kamera",
    "film", "yönetmen", "oyuncu", "senaryo", "belgesel",
    # Matematik ve sayılar
    "sayı", "sıfır", "bir", "iki", "üç", "dört", "beş",
    "altı", "yedi", "sekiz", "dokuz", "on", "yüz", "bin",
    "milyon", "toplam", "fark", "çarpım", "bölüm", "oran",
    "yüzde", "yarım", "çeyrek", "çift", "tek",
    # Diğer sık kullanılan kelimeler
    "hayat", "ölüm", "doğum", "düğün", "cenaze", "bayram",
    "festival", "kutlama", "hediye", "sürpriz", "davet", "misafir",
    "yolculuk", "tatil", "gezi", "macera", "keşif", "harita",
    "pusula", "rehber", "işaret", "sembol", "anlam", "kelime",
    "cümle", "paragraf", "sayfa", "bölüm", "konu", "soru",
    "cevap", "problem", "çözüm", "sonuç", "örnek", "deneyim",
    "tecrübe", "alışkanlık", "gelenek", "kültür", "medeniyet",
    "toplum", "aile", "nesil", "miras", "değer", "ahlak",
    "erdem", "vicdan", "sorumluluk", "görev", "hizmet",
    "yardım", "bağış", "gönüllü", "paylaşım",
    "işbirliği", "rekabet", "yarış", "ödül", "madalya",
    "kupa", "derece", "sıra", "liste", "kayıt", "rapor",
    "sunum", "toplantı", "görüşme", "müzakere", "anlaşma",
    "sözleşme", "imza", "belge", "resmi", "özel",
    "genel", "ortak", "ayrı", "benzer", "farklı", "eşit",
    "üstün", "alt", "üst", "ön", "arka", "yan",
    "orta", "kenar", "köşe", "merkez", "çevre",
    "mesafe", "uzaklık", "yakınlık", "derinlik", "yükseklik",
    "genişlik", "alan", "hacim", "ağırlık",
    "hız", "yön", "hareket", "denge", "basınç",
    "sıcaklık", "ışık", "ses", "renk", "koku",
    "tat", "dokunma", "his", "duygu", "düşünce",
    "hayal", "hafıza", "dikkat", "konsantrasyon",
    "yetenek", "beceri", "bilgi", "deneyim",
    "eğitim", "öğrenme", "gelişim", "ilerleme",
    "değişim", "dönüşüm", "evrim", "devrim",
    "reform", "yenilik", "icat", "buluş", "patent",
    "marka", "reklam", "pazarlama", "strateji", "taktik",
    "politika", "diplomasi", "barış", "silah",
    "ordu", "donanma", "savunma", "saldırı", "çatışma",
    "kriz", "felaket", "afet", "yardım", "kurtarma",
    "güvenlik", "tehlike", "uyarı", "alarm",
    "işaret", "sinyal", "kod", "şifre", "anahtar",
]
