# -*- coding: utf-8-sig -*-
"""
En sık kullanılan 1000 Türkçe kelime.
Günlük bulmaca için başlangıç kelimeleri bu listeden seçilir.
"""

COMMON_TURKISH_WORDS: list[str] = [
    # Sıfatlar
    "güzel", "çirkin", "büyük", "küçük", "uzun", "kısa",
    "geniş", "dar", "kalın", "ince", "ağır", "hafif",
    "hızlı", "yavaş", "sıcak", "soğuk", "sert", "yumuşak",
    "eski", "yeni", "genç", "yaşlı", "zengin", "fakir",
    "kolay", "zor", "doğru", "yanlış", "iyi", "kötü",
    "temiz", "kirli", "açık", "kapalı", "dolu", "boş",
    "tatlı", "acı", "tuzlu", "ekşi", "güçlü", "zayıf",
    "mutlu", "üzgün", "kızgın", "sakin", "sessiz", "gürültülü",
    "parlak", "karanlık", "beyaz", "siyah", "kırmızı", "mavi",
    "yeşil", "sarı", "turuncu", "mor", "pembe", "gri",
    "kahverengi", "altın", "gümüş", "düz", "eğri",
    "yuvarlak", "kare", "derin", "sığ", "taze", "bayat",
    "şık", "zarif", "kaba", "nazik", "cimri", "cömert",
    "cesur", "ürkek", "neşeli", "kederli", "mat", "pürüzlü",
    "pürüzsüz", "lezzetli", "tatsız", "kokulu", "kokusuz", "doğal",
    "yapay", "gerçek", "sahte", "gizli", "aleni", "heyecanlı",
    "yorgun", "zinde", "ıslak", "kuru", "kıymetli", "değersiz",
    "önemli", "önemsiz", "mantıklı", "duygusal", "fiziksel", "kimyasal",
    "sosyal", "kültürel", "ekonomik", "siyasi", "askeri", "hukuki",
    "dini", "sanatsal", "teknik",
    # Aile ve insanlar
    "anne", "baba", "çocuk", "oğul", "kız", "kardeş",
    "abla", "ağabey", "dede", "nine", "amca", "dayı",
    "teyze", "hala", "kuzen", "eş", "arkadaş", "komşu",
    "akraba", "ata", "torun", "damat", "gelin", "kayınvalide",
    "kayınpeder", "yetim", "öksüz", "dul", "bekar", "evli",
    "öğretmen", "öğrenci", "doktor", "hemşire", "avukat", "mühendis",
    "polis", "asker", "çiftçi", "işçi", "memur", "müdür",
    "başkan", "lider", "patron", "şef", "garson", "berber",
    "terzi", "kasap", "fırıncı", "bakkal", "eczacı", "dişçi",
    "komutan", "vali", "kaymakam", "bakan", "müsteşar", "esnaf",
    "sanatçı", "usta", "çırak", "kalfa", "bebek", "kadın",
    "erkek", "insan", "toplum",
    # Vücut
    "baş", "göz", "kulak", "burun", "ağız", "dil",
    "el", "parmak", "kol", "bacak", "ayak", "kalp",
    "beyin", "kan", "kemik", "saç", "yüz", "boyun",
    "omuz", "sırt", "göğüs", "karın", "diz", "bilek",
    "deri", "tırnak", "kirpik", "kaş", "dudak", "çene",
    "yanak", "alın", "ense", "boğaz", "akciğer", "karaciğer",
    "mide", "böbrek", "damar", "sinir", "hücre", "doku",
    "iskelet",
    # Doğa
    "güneş", "ay", "yıldız", "dünya", "gökyüzü", "bulut",
    "yağmur", "kar", "rüzgar", "fırtına", "sel", "deprem",
    "dağ", "tepe", "vadi", "ova", "orman", "ağaç",
    "çiçek", "yaprak", "kök", "dal", "çimen", "toprak",
    "taş", "kaya", "kum", "deniz", "okyanus", "göl",
    "nehir", "çay", "şelale", "ada", "sahil", "plaj",
    "mağara", "volkan", "çöl", "buz", "ateş", "duman",
    "alev", "hava", "iklim", "mevsim", "ilkbahar", "yaz",
    "sonbahar", "kış", "gece", "gündüz", "sabah", "öğle",
    "akşam", "şafak", "gün", "hafta", "yıl",
    "evren", "uzay", "gezegen", "meteor", "atmosfer", "şimşek",
    "sis", "buhar", "uçurum", "yarımada", "körfez", "rıhtım",
    "vaha", "bataklık", "bozkır", "yayla", "mera", "kaynak",
    "dere", "batı", "doğu", "kuzey", "güney",
    # Hayvanlar
    "kedi", "köpek", "kuş", "balık", "at", "inek",
    "koyun", "keçi", "tavuk", "horoz", "ördek", "kaz",
    "arı", "karınca", "kelebek", "örümcek", "yılan", "kurbağa",
    "kaplumbağa", "timsah", "aslan", "kaplan", "ayı", "kurt",
    "tilki", "tavşan", "fare", "sincap", "maymun", "fil",
    "zürafa", "deve", "yunus", "balina", "köpekbalığı", "kartal",
    "baykuş", "papağan", "penguen", "yarasa", "böcek", "sinek",
    "sivrisinek", "akrep", "suaygırı", "gergedan", "kanguru", "koala",
    "panda", "kunduz", "sansar", "gelincik", "kirpi", "köstebek",
    "şahin", "doğan", "atmaca", "leylek", "kırlangıç", "serçe",
    "bülbül", "sülün", "bıldırcın", "kuğu", "martı", "fok",
    "mors", "ıstakoz", "yengeç", "karides", "ahtapot", "mercan",
    "sünger", "denizanası", "denizyıldızı", "denizatı",
    # Yiyecek ve içecek
    "ekmek", "su", "süt", "çay", "kahve", "meyve",
    "sebze", "et", "pirinç", "makarna", "peynir", "yoğurt",
    "tereyağı", "yumurta", "şeker", "tuz", "biber", "soğan",
    "sarımsak", "domates", "salatalık", "patates", "havuç", "kabak",
    "patlıcan", "fasulye", "mercimek", "nohut", "elma", "portakal",
    "muz", "üzüm", "çilek", "karpuz", "kavun", "şeftali",
    "kiraz", "erik", "armut", "limon", "zeytin", "fındık",
    "ceviz", "badem", "pilav", "çorba", "salata", "börek",
    "simit", "pasta", "dondurma", "bal", "reçel", "turşu",
    "un", "yağ", "sirke", "limonata", "ayran", "şerbet",
    "pekmez", "tahin", "helva", "lokum", "sucuk", "salam",
    "sosis", "pastırma", "kavurma", "köfte", "kebap", "döner",
    "pide", "lahmacun", "mantı", "kısır", "cacık",
    # Ev ve eşyalar
    "ev", "oda", "kapı", "pencere", "duvar", "tavan",
    "zemin", "merdiven", "balkon", "bahçe", "mutfak", "banyo",
    "yatak", "masa", "sandalye", "koltuk", "dolap", "ayna",
    "lamba", "perde", "halı", "yastık", "battaniye", "havlu",
    "tabak", "bardak", "kaşık", "çatal", "bıçak", "tencere",
    "tava", "fırın", "buzdolabı", "televizyon", "telefon",
    "bilgisayar", "saat", "anahtar", "kilit", "çanta",
    "çaydanlık", "cezve", "tepsi", "kase", "sürahi", "kavanoz",
    "kutu", "sepet", "fırça", "süpürge", "faraş", "kova",
    "leğen", "sabun", "şampuan", "macun", "tarak", "makas",
    "iğne", "iplik", "askı", "ütü",
    # Giyim
    "elbise", "gömlek", "pantolon", "etek", "ceket", "palto",
    "ayakkabı", "çorap", "şapka", "eldiven", "atkı", "kravat",
    "kemer", "düğme", "cep", "kumaş", "ipek", "pamuk",
    "deri", "yün", "yelek", "hırka", "kazak", "süveter",
    "mont", "kaban", "yağmurluk", "bornoz", "pijama", "gecelik",
    "atlet", "terlik", "bot", "çizme", "sandalet", "toka",
    "küpe", "kolye", "bilezik", "yüzük", "gözlük",
    # Ulaşım
    "araba", "otobüs", "tren", "uçak", "gemi", "bisiklet",
    "motosiklet", "taksi", "tramvay", "metro", "köprü", "tünel",
    "yol", "cadde", "sokak", "kavşak", "park", "otopark",
    "benzin", "tekerlek", "motor", "fren", "direksiyon", "kask",
    "kamyon", "kamyonet", "minibüs", "midibüs", "karavan", "traktör",
    "dozer", "vinç", "itfaiye", "ambulans", "römorkör", "sandal",
    "yat", "feribot", "vapur",
    # Şehir ve yapılar
    "şehir", "köy", "kasaba", "mahalle", "bina", "apartman",
    "okul", "hastane", "cami", "kilise", "kütüphane", "müze",
    "tiyatro", "sinema", "stadyum", "market", "çarşı", "pazar",
    "banka", "postane", "otel", "restoran", "kafe", "fabrika",
    "havaalanı", "liman", "istasyon", "kule", "kale",
    "saray", "köşk", "konak", "yalı", "villa", "kulübe",
    "çadır", "kışla", "adliye", "valilik", "belediye", "muhtarlık",
    "eczane", "kırtasiye", "kuyumcu", "manav",
    # Eğitim ve bilim
    "kitap", "defter", "kalem", "kağıt", "tahta", "sınıf",
    "ders", "sınav", "not", "ödev", "diploma", "üniversite",
    "bilim", "matematik", "fizik", "kimya", "biyoloji", "tarih",
    "coğrafya", "edebiyat", "felsefe", "sanat", "müzik", "resim",
    "heykel", "şiir", "roman", "hikaye", "makale", "gazete",
    "dergi", "haber", "araştırma", "deney", "teori", "formül",
    "laboratuvar", "arşiv", "sözlük", "ansiklopedi", "atlas", "küre",
    "mikroskop", "teleskop", "büyüteç", "cetvel", "gönye", "pergel",
    "silgi", "kalemtıraş", "tebeşir",
    # İş ve ekonomi
    "para", "kredi", "borç", "maaş", "vergi",
    "fiyat", "ucuz", "pahalı", "indirim", "kâr", "zarar",
    "şirket", "mağaza", "dükkan", "ticaret", "piyasa", "ekonomi",
    "bütçe", "yatırım", "sigorta", "emekli", "sendika",
    "döviz", "borsa", "hisse", "tahvil", "çek", "senet",
    "fatura", "makbuz", "kasa", "cüzdan",
    # Hukuk ve devlet
    "kanun", "hak", "adalet", "mahkeme", "hakim", "savcı",
    "suç", "ceza", "hapis", "özgürlük", "demokrasi", "seçim",
    "oy", "parti", "hükümet", "meclis", "anayasa", "vatan",
    "millet", "bayrak", "sınır", "pasaport", "vize",
    "tüzük", "yönetmelik", "genelge", "kararname", "ferman", "berat",
    "mühür", "parmakizi",
    # Duygular ve soyut kavramlar
    "sevgi", "aşk", "nefret", "korku", "umut", "hayal",
    "rüya", "gerçek", "yalan", "sır", "güven", "inanç",
    "din", "tanrı", "ruh", "akıl", "düşünce", "fikir",
    "plan", "hedef", "amaç", "başarı", "zafer", "yenilgi",
    "barış", "savaş", "tehlike", "güvenlik", "risk", "şans",
    "kader", "talih", "mutluluk", "huzur", "özlem", "merak",
    "şaşkınlık", "gurur", "utanç", "kıskançlık", "öfke", "sabır",
    "cesaret", "korkaklık", "dürüstlük", "sadakat", "ihanet",
    "dostluk", "düşmanlık", "yalnızlık", "merhamet", "şefkat",
    "minnet", "vefa", "hüzün", "keder", "neşe", "sevinç",
    "coşku", "heyecan", "kabus", "kurgu", "hakikat",
    # Zaman
    "zaman", "dakika", "saniye", "bugün", "dün", "yarın",
    "önce", "sonra", "şimdi", "geçmiş", "gelecek", "takvim",
    "dönem", "çağ", "asır", "süre", "erken",
    "geç", "hemen", "bazen", "sık", "nadir", "daima",
    "hiç", "her", "gurup", "mehtap", "milat", "devir",
    "kuşak",
    # Sağlık
    "sağlık", "hastalık", "ilaç", "ağrı", "ateş", "yara",
    "ameliyat", "tedavi", "aşı", "mikrop", "virüs", "bakteri",
    "kanser", "grip", "alerji", "tansiyon", "diyabet",
    "nefes", "öksürük", "hapşırık", "teşhis", "reçete",
    "sargı", "alçı", "protez", "şırınga", "termometre", "stetoskop",
    # Spor ve eğlence
    "futbol", "basketbol", "voleybol", "tenis", "yüzme", "koşu",
    "boks", "güreş", "jimnastik", "kayak", "golf", "satranç",
    "oyun", "maç", "takım", "gol", "hakem", "skor",
    "şampiyon", "turnuva", "olimpiyat", "antrenman", "atletizm",
    "hentbol", "beyzbol", "ragbi", "kriket", "sörf", "yelken",
    "kürek", "dağcılık", "kamp", "piknik", "lunapark", "sirk",
    # Teknoloji
    "teknoloji", "internet", "program", "yazılım", "donanım", "ekran",
    "klavye", "şifre", "veri", "dosya", "belge",
    "mesaj", "eposta", "uygulama", "robot", "yapay", "zeka",
    "enerji", "elektrik", "pil", "kablo", "uydu", "radar",
    "mikroçip", "işlemci", "bellek", "disk", "modem", "yönlendirici",
    "antivirüs", "tarayıcı", "yazıcı", "hoparlör", "kulaklık", "mikrofon",
    "projeksiyon",
    # Coğrafya ve ülkeler
    "türkiye", "istanbul", "ankara", "izmir", "avrupa", "asya",
    "afrika", "amerika", "kıta", "ülke", "başkent",
    "nüfus", "harita", "pusula", "ekvator", "kutup",
    # Müzik ve sanat
    "şarkı", "melodi", "ritim", "enstrüman", "gitar", "piyano",
    "davul", "keman", "flüt", "konser", "sahne", "orkestra",
    "dans", "bale", "tablo", "sergi", "fotoğraf", "kamera",
    "film", "yönetmen", "oyuncu", "senaryo", "belgesel",
    "nota", "makam", "usul", "beste", "güfte", "solist",
    "koro", "balet", "balerin", "aktör", "aktris", "dublaj",
    "montaj",
    # Diğer sık kullanılan kelimeler
    "hayat", "ölüm", "doğum", "düğün", "cenaze", "bayram",
    "festival", "kutlama", "hediye", "sürpriz", "davet", "misafir",
    "yolculuk", "tatil", "gezi", "macera", "keşif", "rehber",
    "işaret", "sembol", "anlam", "kelime",
    "cümle", "paragraf", "sayfa", "bölüm", "konu", "soru",
    "cevap", "problem", "çözüm", "sonuç", "örnek", "deneyim",
    "alışkanlık", "gelenek", "kültür", "medeniyet", "nesil",
    "miras", "değer", "ahlak", "erdem", "vicdan", "sorumluluk",
    "görev", "hizmet", "bağış", "gönüllü", "paylaşım",
    "işbirliği", "rekabet", "yarış", "ödül", "madalya",
    "kupa", "derece", "sıra", "liste", "kayıt", "rapor",
    "sunum", "toplantı", "görüşme", "müzakere", "anlaşma",
    "sözleşme", "imza", "özel",
    "genel", "ortak", "ayrı", "benzer", "farklı", "eşit",
    "üstün", "alt", "üst", "ön", "arka", "yan",
    "orta", "kenar", "köşe", "merkez", "çevre",
    "mesafe", "uzaklık", "yakınlık", "derinlik", "yükseklik",
    "genişlik", "alan", "hacim", "ağırlık",
    "hız", "yön", "hareket", "denge", "basınç",
    "sıcaklık", "ışık", "ses", "renk", "koku",
    "tat", "dokunma", "his", "duygu",
    "hafıza", "dikkat", "konsantrasyon",
    "yetenek", "beceri", "bilgi",
    "eğitim", "öğrenme", "gelişim", "ilerleme",
    "değişim", "dönüşüm", "evrim", "devrim",
    "reform", "yenilik", "icat", "buluş", "patent",
    "marka", "reklam", "pazarlama", "strateji", "taktik",
    "politika", "diplomasi", "silah",
    "ordu", "donanma", "savunma", "saldırı", "çatışma",
    "kriz", "felaket", "afet", "kurtarma",
    "uyarı", "alarm", "kod",
]
